# =============================================================================
# OmniGibson Environment Configuration
# =============================================================================

# Environment Basic Settings
env:
  action_frequency: 30
  physics_frequency: 120
  device: null
  automatic_reset: false
  flatten_action_space: false
  flatten_obs_space: false
  use_external_obs: false
  initial_pos_z_offset: 0.1

# Render Settings
render:
  viewer_width: 1280
  viewer_height: 720

# Scene Configuration
scene:
  type: InteractiveTraversableScene
  scene_model: Rs_int
  load_object_categories: [floors, walls, ceilings]
  not_load_object_categories: null
  trav_map_resolution: 0.1
  seg_map_resolution: 0.1
  trav_map_with_objects: true
  num_waypoints: 1
  waypoint_resolution: 0.2
  load_room_types: null
  load_room_instances: null
  load_task_relevant_only: false
  scene_source: OG
  include_robots: false

# Robot Configuration
robots:
  - type: Tiago
    # Basic Settings
    obs_modalities: [rgb, proprio]
    proprio_obs: default
    scale: 1.0
    self_collisions: true
    action_normalize: false
    action_type: continuous
    grasping_mode: sticky
    
    # Trunk Configuration
    rigid_trunk: true
    default_trunk_offset: 0.3
    
    # Arm Pose Configuration
    # Available poses: vertical, diagonal15, diagonal30, diagonal45, horizontal
    default_arm_pose: horizontal
    
    # Robot Position
    position: [0.7, -0.5, 0.0]
    
    # Joint Reset Positions
    reset_joint_pos: [
      # Base joints (6 DOF: x, y, z, rx, ry, rz)
      0.000,   # base_footprint_x_joint
      0.000,   # base_footprint_y_joint
      0.000,   # base_footprint_z_joint
      0.000,   # base_footprint_rx_joint
      0.000,   # base_footprint_ry_joint
      0.000,   # base_footprint_rz_joint
      
      # Trunk
      0.320,   # torso_lift_joint
      
      # Arms (7 DOF each)
      0.615,   # arm_left_1_joint
      0.615,   # arm_right_1_joint
      0.000,   # head_1_joint
      0.492,   # arm_left_2_joint
      0.492,   # arm_right_2_joint
      -1.000,  # head_2_joint
      1.463,   # arm_left_3_joint
      1.463,   # arm_right_3_joint
      1.249,   # arm_left_4_joint
      1.249,   # arm_right_4_joint
      1.083,   # arm_left_5_joint
      1.083,   # arm_right_5_joint
      -1.289,  # arm_left_6_joint
      -1.289,  # arm_right_6_joint
      1.509,   # arm_left_7_joint
      1.509,   # arm_right_7_joint
      
      # Grippers
      0.045,   # gripper_left_left_finger_joint
      0.045,   # gripper_left_right_finger_joint
      0.045,   # gripper_right_left_finger_joint
      0.045    # gripper_right_right_finger_joint
    ]
    
    # Sensor Configuration
    sensor_config:
      VisionSensor:
        modalities: [rgb]
        enabled: true
        noise_type: null
        noise_kwargs: null
        sensor_kwargs:
          image_width: 640
          image_height: 480
          focal_length: 12.0
          clipping_range: [0.01, 10.0]
    
    # Controller Configuration
    controller_config:
      base:
        name: JointController
      arm_left:
        name: InverseKinematicsController
      arm_right:
        name: InverseKinematicsController
      gripper_left:
        name: MultiFingerGripperController
      gripper_right:
        name: MultiFingerGripperController
      camera:
        name: JointController

# Objects Configuration
objects:
  - type: DatasetObject
    name: table
    category: breakfast_table
    model: lcsizg
    fixed_base: true
    position: [1.5, -0.5, 0.5]
    orientation: [0, 0, 0.707, 0.707]
    scale: [1, 1, 1]

# Random Table Objects Configuration
random_table_objects:
  # Table Information
  table_name: table
  table_length: 1.5
  table_width: 0.8
  table_height: 0.6
  
  # Object Categories and Quantities
  categories: [apple, mug, tablefork, bowl, can, can_of_beans, can_of_soda]
  num_objects: [1, 1, 1, 1, 1, 1, 1]  # One of each category
  
  # Generation Settings
  random_models: true
  padding: 0.1          # Edge padding from table edges (meters)
  occupancy_rate: 0.8     # Density of objects on table surface
  grid_size: 0.15         # Size of each grid cell (meters)
  auto_supplement: true   # Add more objects if space allows

# Task Configuration
task:
  type: DummyTask